- name: Create a instance
  hosts: localhost

  vars:
    keypair: test
    instance_type: t2.micro
    security_group: default
    image: ami-09d95fab7fff3776c
    region: us-east-1
    vpc_subnet_id: subnet-58455b12
  tasks:
    - name: Create EFS
      efs:
        state: present
        name: efs-workpress
        targets:
          - subnet_id: "{{ vpc_subnet_id }}"
            security_groups: "{{ security_group }}"