- name: Create a instance
  hosts: localhost

  vars:
    keypair: test
    instance_type: t2.micro
    security_group: default
    image: ami-09d95fab7fff3776c
    region: us-east-1
    vpc_subnet_id: subnet-58455b12
  tasks:
    - name: Launch instance
      ec2:
        key_name: "{{ keypair }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        count: 1
        region: "{{ region }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: no
      register: ec2_out

    - name: Create RDS
      rds:
        command: create
        instance_name: master-db
        db_engine: MySQL
        size: 10
        instance_type: db.t2.micro
        availability_zone: us-east-1a
        username: mysql_admin
        password: password
        read_replica: yes
        tags:
          Environment: dev
          Application: cms

      rds:
        command: replicate
        instance_name: replica-db
        source_instance: master-db
        wait: yes
        wait_timeout: 600

    - name: Create a public zone
      route53_zone:
        zone: test.com
        comment: public zone

    - name: Create alias
      route53:
        state: present
        zone: test.com
        record: elb.test.com
        type: CNAME
        value: "{{ elb.dns_name }}"
        alias: True

    - name: Create EFS
      efs:
        state: present
        name: efs-workpress
        targets:
          - subnet_id: "{{ vpc_subnet_id }}"
            security_groups: "{{ security_group }}"